name: Build Kiryuu Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kiryuu Extension
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt

      - name: Build Kiryuu APK
        run: |
          ./gradlew :multisrc:overrides:wpmangareader:kiryuu:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: kiryuu-apk
          path: multisrc/overrides/wpmangareader/kiryuu/build/outputs/apk/debug/*.apk

      - name: Provide download link
        run: |
          echo "Download your APK here: https://github.com/${{ github.repository }}/actions/artifacts"