name: Build and Upload APK

# Trigger manually from GitHub interface
on:
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 8 (since user prefers Java 8)
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      # Step 3: Build the project using Gradle
      - name: Build the project
        run: ./gradlew build

      # Step 4: Upload the APK artifact to GitHub
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: build/outputs/apk/release/your_app.apk  # Ganti dengan nama dan lokasi APK yang sesuai
