name: Build single extension

on:
  workflow_dispatch:
    inputs:
      lang:
        description: Extension language (en, ar, es, pt...)
        required: false
        default: 'id'  # Set default language to 'id'
      extension:
        description: Target extension name
        required: false
        default: 'kiryuu'  # Set default extension name to 'kiryuu'
      ismultisrc:
        type: boolean
        description: Its a multisrc extension
        default: false
        required: false
      git-repo:
        description: Git repo (Optional, defaults to imgview/tachip)
        default: 'imgview/tachip'  # Set default repo
        required: false
      git-ref:
        description: Git Ref (Optional, defaults to kiwi)
        default: 'kiwi'  # Set default branch to 'kiwi'
        required: false

env:
  BASEPATH: src
  EXTPATH: ${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}
  BASESLUG: individual
  EXTSLUG: ${{ github.event.inputs.lang }}:${{ github.event.inputs.extension }}
  REPO: ${{ github.event.inputs.git-repo }}
  CI_MODULE_GEN: true
  CI_MULTISRC: ${{ github.event.inputs.ismultisrc }}
  CI_MATRIX_LANG: ${{ github.event.inputs.lang }}

jobs:
  build-extension:
    name: Build a single extension
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          set -e
          if [[ -z "${{ env.REPO }}" ]]; then
            echo "REPO=${{ github.repository_owner }}/tachip" >> $GITHUB_ENV
          fi
          if [[ ${{ github.event.inputs.ismultisrc }} != false ]]; then
            echo "BASEPATH=generated-src" >> $GITHUB_ENV
            echo "BASESLUG=multisrc" >> $GITHUB_ENV
          fi

      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt

      - name: Generate multisrc extensions
        if: ${{ github.event.inputs.ismultisrc == 'true' }}
        run: |
          ./gradlew generateExtensions

      - name: Build APK
        run: |
          ./gradlew :multisrc:overrides:wpmangareader:${{ github.event.inputs.extension }}:assembleDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{github.event.inputs.lang}}-${{ github.event.inputs.extension }}
          path: "${{ env.BASEPATH }}/${{ env.EXTPATH }}/build/outputs/apk/debug/*.apk"
          retention-days: 1
