name: Build and Upload APK

on:
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build the project
        run: ./gradlew build

      - name: List build directory
        run: ls -R build/outputs/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: individual-apks-2
          path: '**/*.apk'  # Mencari semua file APK
