name: Build Kiryuu Extension

on:
  push:
    branches:
      - main  # Ganti dengan nama cabang yang sesuai jika diperlukan
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kiryuu-artifact
          path: path/to/your/build/output  # Ganti dengan jalur keluaran build Anda

      - name: Create Download Link
        run: |
          echo "Download your artifact here: https://github.com/${{ github.repository }}/actions/artifacts"
