name: Send APK via Email

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Recipient Email'
        required: true
      password:
        description: 'Email Password'
        required: true
      subject:
        description: 'Email Subject'
        required: true
      body:
        description: 'Email Body'
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the project
        run: ./gradlew build

      - name: Send Email with Attachment
        uses: mattmccutchen/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 587
          smtp-user: ${{ github.event.inputs.email }}
          smtp-password: ${{ github.event.inputs.password }}
          to: ${{ github.event.inputs.email }}
          subject: ${{ github.event.inputs.subject }}
          body: ${{ github.event.inputs.body }}
          attachments: build/outputs/apk/release/your_app.apk  # Ganti dengan nama file APK Anda
