name: Build and Upload Kiryuu APK

on:
  workflow_dispatch: # Tombol "Run workflow"
  push:
    branches:
      - kiwi
  pull_request:
    branches:
      - kiwi

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8] # Menggunakan Java 8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AdoptOpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt # Menggunakan AdoptOpenJDK

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Kiryuu APK
      run: ./gradlew :multisrc:overrides:wpmangareader:kiryuu:assembleRelease # Path Gradle untuk membuild APK dari Kiryuu.kt

    - name: Upload Kiryuu APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: kiryuu-apk
        path: ./multisrc/overrides/wpmangareader/kiryuu/build/outputs/apk/release/*.apk # Path APK yang dibuild
