name: Build and Upload APK

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: [all, en]  # Ubah sesuai kebutuhan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # Menggunakan Java 11

      - name: Build "${{ matrix.lang }}" extensions
        uses: gradle/gradle-command-action@v2
        env:
          CI_MULTISRC: "false"
          CI_MATRIX_LANG: ${{ matrix.lang }}
          ALIAS: ${{ secrets.ALIAS }}  # Ganti atau hapus jika tidak perlu
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}  # Ganti atau hapus jika tidak perlu
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}  # Ganti atau hapus jika tidak perlu
        with:
          arguments: assembleRelease  # Gunakan assembleDebug jika perlu
          cache-disabled: true

      - name: Upload "${{ matrix.lang }}" APKs
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.lang }}-apks"
          path: "**/*.apk"
