name: Build Kuryuu

on:
  workflow_dispatch:  # Memungkinkan workflow dijalankan secara manual
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Versi JDK yang Anda inginkan
        distribution: 'temurin'  # Menentukan distribusi JDK (misalnya: temurin, adopt, zulu)

    - name: Build Kuryuu
      env:
        CI: true  # Set variabel lingkungan untuk mendeteksi CI
        CI_MATRIX_LANG: 'id'  # Bahasa yang digunakan untuk build
      run: |
        ./gradlew assembleDebug -p src/id/bacakomik  # Ubah path sesuai dengan lokasi Kuryuu

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kuryuu-apk
        path: src/id/bacakomik/build/outputs/apk/debug/app-debug.apk  # Sesuaikan dengan lokasi APK Anda
