name: Java CI

on:
  workflow_dispatch: # Mengaktifkan tombol "Run workflow" secara manual
  push:
    branches:
      - kiwi
  pull_request:
    branches:
      - kiwi

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8] # Menggunakan Java 8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AdoptOpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt # Menggunakan AdoptOpenJDK

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
