name: Build Tachiyomi Extension

on:
  push:
    branches:
      - anu
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Install Gradle 7.4
        run: |
          wget https://services.gradle.org/distributions/gradle-7.4-bin.zip
          unzip gradle-7.4-bin.zip
          sudo mv gradle-7.4 /opt/gradle
          sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle

      - name: Build the project
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifact
          path: build/outputs/apk/release/*.apk
